#!/usr/bin/env bash
set -e
export VAULT_ADDR='https://ebola2018.dide.ic.ac.uk:8200'
vault login -method=github

vault write /secret/database/users/postgres value=$(pwgen 70 1)
vault write /secret/database/users/orderly value=$(pwgen 70 1)
vault write /secret/database/users/readonly value=$(pwgen 70 1)
vault write /secret/database/users/import value=$(pwgen 70 1)
